version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - revive
    - misspell
    - prealloc
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - fmt.Fprintf
        - fmt.Fprintln
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives

formatters:
  enable:
    - gofmt
