name: Publish binaries

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:
    inputs: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # create GitHub releases

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50
        persist-credentials: false

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22'
        cache: false

    - name: Build
      run: |
        make
        for asset in ./bin/*; do
          xz -9 "${asset}"
        done

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        assets=()
        for asset in ./bin/*.xz; do
          assets+=("-a" "${asset}")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
